### ISSUE TITLE
query with format=json returns parse error

### ISSUE THREAD

**Issue by chreman** [njahn82/ropenaire#6] opened 2018-03-05 23:29 UTC
example:
```> 
library(ropenaire)
pubs <- roa_pubs(fp7 = "283595", format='json')
Error: parse error: after key and value, inside map, I expect ',' or '}'
          "dnet:result_subject", "$" : 020 }, { "@classid" : "keyword"
                     (right here) ------^
```
in this example works fine for roa_datasets

**Comment by sckott** [comment] 2018-03-05 23:41
it's an error in the `jsonlite` R library - i'm guesssing it's a problem on the Openaire side though since `020` should either be a numeric like `20` or if they want `020`, then it should be a string `"020"`  

ping @njahn82  @alessiabardi  

to get this on the command line: 

```
curl -v 'http://api.openaire.eu/search/publications?FP7ProjectID=283595&size=1000&format=json'
```

to reproduce in R:

```r
install.packages("remotes")
remotes::install_github("sckott/ropenaire")
library(ropenaire)
roa_pubs(fp7 = "283595", format='json', verbose = TRUE)
```

**Comment by njahn82** [comment] 2018-03-06 07:58
Thank you for reporting this, we will look into it.

**Comment by joschirr** [comment] 2018-03-06 09:09
This specific issue is likely caused by a missing classification scheme for the subject.
We may introduce a "custom prefix" to avoid that the "number" is interpreted as a numeric value.
Likely it should read "ddc:020" but the "ddc" classification scheme couldn't be determined in this case.

**Comment by sckott** [comment] 2018-03-06 17:19
here's some SO info on this if it helps https://stackoverflow.com/questions/27361565/why-is-json-invalid-if-an-integer-begins-with-0

**Comment by sckott** [comment] 2018-03-09 16:15
Added temporary fix for this - it's not really a fix but at least stops with an error saying bad json if the json is bad - and a fallout to get raw text if you like `roa_pubs(..., raw = TRUE)`

**Comment by sckott** [comment] 2018-04-24 13:19
looks like this is sorted out, can you close @njahn82 ?

**Closed as completed** 2018-04-25 14:32 UTC
